version: '3'
services:
  node:
    build:
      context: .
    volumes:
      - ./:/usr/src
      - node-modules:/usr/src/app/node_modules
    command: sh -c "yarn install && yarn start"
    tty: true
    ports:
     - "3000:3000"
volumes:
  node-modules:
    driver: local